[package]
name = "sweeper_rs"
version = "0.1.0"
authors = ["serpro <none>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "3.0.2"
chrono = "0.4.19"